name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compile Executable
      run: dotnet publish CallApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true

    - name: Upload App Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CallApp-EXE
        path: bin/Release/net8.0/win-x64/publish/CallApp.exe
