name: Build and Release Windows Executable

on:
  push:
    tags:
      - 'v*' # Triggers whenever you push a tag like v1.0, v1.1, etc.
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Compile Executable
      run: dotnet publish CallApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true

    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: bin/Release/net8.0/win-x64/publish/CallApp.exe
